apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $files := .Files }}
  {{- range tuple "config1.toml" "config2.toml" "config3.toml" }}
  {{ . }}: |-
    {{ $files.Get . }}
  {{- end }}
  {{ range $path, $_ :=  .Files.Glob  "**.yaml" }}
  {{ $.Files.Get $path }}
  {{ end }}
