apiVersion: v1
kind: Pod
metadata:
  name: fortune-args
spec:
  containers:
    - name: html-generator
      image: luksa/fortune:args
      args:
        - "2"
      volumeMounts:
        - mountPath: /var/htdocs
          name: html
    - name: web-server
      image: nginx:alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: html
      emptyDir:
        {}
