apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-deployment
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: kubia-pod
      labels:
        app: kubia
    spec:
      containers:
        - image: luksa/kubia:v3
          name: kubia-container
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: 8080
  selector:
    matchLabels:
      app: kubia
