apiVersion: v1
kind: Pod
metadata:
  name: requests-limits-pod
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: ["dd", "if=/dev/zero", "of=/dev/null"]
      resources:
        requests:
          cpu: 1000m
          memory: 10Mi
        limits:
          cpu: 1000m
          memory: 10Mi
