apiVersion: v1
kind: ReplicationController
metadata:
  name: my-first-rc01
spec:
  replicas: 3
#  selector 是可选的
  selector:
    app: my-first-app01
  template:
    metadata:
      labels:
        app: my-first-app01
    spec:
      containers:
        - name: my-first-image
          image: zhyyu2016/my-first-image
          ports:
            - containerPort: 8088
