apiVersion: v1
kind: Pod
metadata:
  name: fortune-hostpath
spec:
  containers:
    - name: html-generator
      image: luksa/fortune
      volumeMounts:
        - mountPath: /var/htdocs
          name: myhostpath
    - name: web-server
      image: nginx:alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: myhostpath
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: myhostpath
      hostPath:
        path: /jurorhostpath
